# Tensors: The Core of PyTorch

Has visto que el viaje de construir una red neuronal comienza con los datos. Antes de que puedas diseñar un modelo o iniciar el proceso de entrenamiento, debes reunir tu información y prepararla en un formato que el modelo pueda entender. En PyTorch, ese formato fundamental es el **tensor**. Los tensores son más que simples contenedores de datos; están optimizados para las operaciones matemáticas que impulsan el deep learning.

Dominar los tensores es un paso vital. Muchos de los errores más comunes al construir modelos están relacionados con las formas (shapes), tipos o dimensiones de los tensores. Este laboratorio está diseñado para darte una base sólida en la manipulación de tensores, brindándote las habilidades para manejar datos de manera efectiva y depurar problemas con confianza.

En este laboratorio, aprenderás cómo:

* Crear tensores a partir de diferentes fuentes de datos como listas de Python y arrays de NumPy.

* Cambiar la forma (reshape) y manipular las dimensiones de los tensores para preparar los datos para las entradas del modelo.

* Usar técnicas de indexación (indexing) y segmentación (slicing) para acceder y filtrar partes específicas de tus datos.

* Realizar las operaciones matemáticas y lógicas que forman la base de todos los cálculos de las redes neuronales.

Al final de este notebook, tendrás las habilidades prácticas necesarias para gestionar con confianza los datos de cualquier proyecto de PyTorch.

## Imports

In [1]:
import torch
import numpy as np
import pandas as pd

## 1 - Tensor Creation

El primer paso en cualquier pipeline de machine learning es preparar los datos para el modelo. En PyTorch, esto significa cargar tus datos en tensores. Verás que existen varias formas convenientes de crear tensores, ya sea que tus datos ya estén en otro formato o que necesites generarlos desde cero.

### 1.1 From Existing Data Structures

A menudo, tus datos brutos estarán en un formato común como una lista de Python, un array de NumPy o un DataFrame de pandas. PyTorch ofrece funciones directas para convertir estas estructuras en tensores, lo que hace que la etapa de preparación de datos sea más eficiente.

* `torch.tensor()`: Esta función toma una entrada, como una lista de Python, para convertirla en un tensor.

**Nota:** El tipo de números que utilices es importante. Si usas números enteros (integers), PyTorch los almacena como tales. Si incluyes decimales, se almacenarán como valores de punto flotante (floating point).

In [3]:
# Desde listas de Python
x = torch.tensor([1, 2, 3])

print("DESDE LISTAS DE PYTHON:", x)
print("TIPO DE DATO DEL TENSOR:", x.dtype)

DESDE LISTAS DE PYTHON: tensor([1, 2, 3])
TIPO DE DATO DEL TENSOR: torch.int64


<br>

* `torch.from_numpy()`: Convierte un array de NumPy en un tensor de PyTorch.

In [4]:
#  Desde un array de NumPy 
numpy_array = np.array([[1, 2, 3], [4, 5, 6]])
torch_tensor_from_numpy = torch.from_numpy(numpy_array)

print("TENSOR DESDE NUMPY:\n\n", torch_tensor_from_numpy)

TENSOR DESDE NUMPY:

 tensor([[1, 2, 3],
        [4, 5, 6]])


<br>

* **Desde un DataFrame de pandas**: Pandas es una librería de Python para trabajar con datos organizados en filas y columnas, como un archivo CSV o una hoja de cálculo. Un DataFrame es la estructura de datos principal de pandas para almacenar este tipo de datos tabulares. Los DataFrames son una de las formas más comunes de cargar y explorar conjuntos de datos en machine learning, especialmente al leer archivos CSV. No existe una función directa para convertir un DataFrame a un tensor. El método estándar consiste en extraer los datos del DataFrame a un array de NumPy utilizando el atributo `.values` y luego convertir ese array en un tensor usando `torch.tensor()`.

In [5]:
#  Desde un DataFrame de Pandas
# Leer los datos del archivo CSV en un DataFrame
df = pd.read_csv('./data.csv')

# Extraer los datos como un array de NumPy desde el DataFrame
all_values = df.values

# Convertir los valores del DataFrame a un tensor de PyTorch
tensor_from_df = torch.tensor(all_values)

print("DATAFRAME ORIGINAL:\n\n", df)
print("\nTENSOR RESULTANTE:\n\n", tensor_from_df)
print("\nTIPO DE DATO DEL TENSOR:", tensor_from_df.dtype)

DATAFRAME ORIGINAL:

    distance_miles  delivery_time_minutes
0            1.60                   7.22
1           13.09                  32.41
2            6.97                  17.47

TENSOR RESULTANTE:

 tensor([[ 1.6000,  7.2200],
        [13.0900, 32.4100],
        [ 6.9700, 17.4700]], dtype=torch.float64)

TIPO DE DATO DEL TENSOR: torch.float64


### 1.2 - With Predefined Values

A veces necesitas crear tensores para propósitos específicos, como inicializar los pesos (weights) y sesgos (biases) de un modelo antes de que comience el entrenamiento. PyTorch te permite generar rápidamente tensores llenos de valores provisionales como ceros, unos o números aleatorios, lo cual es útil para pruebas y configuración.

* `torch.zeros()`: Crea un tensor lleno de ceros con las dimensiones especificadas.

In [6]:
# All zeros
zeros = torch.zeros(2, 3)

print("TENSOR WITH ZEROS:\n\n", zeros)

TENSOR WITH ZEROS:

 tensor([[0., 0., 0.],
        [0., 0., 0.]])


<br>

* `torch.ones()`: Crea un tensor lleno de unos con las dimensiones especificadas.

In [7]:
# All ones
ones = torch.ones(2, 3)

print("TENSOR WITH ONES:\n\n", ones)

TENSOR WITH ONES:

 tensor([[1., 1., 1.],
        [1., 1., 1.]])


<br>

* `torch.rand()`: Genera un tensor con números aleatorios distribuidos uniformemente entre 0 y 1, basándose en las dimensiones especificadas.

In [8]:
# Random numbers
random = torch.rand(2, 3)

print("RANDOM TENSOR:\n\n", random)

RANDOM TENSOR:

 tensor([[0.9672, 0.1337, 0.5241],
        [0.9266, 0.1321, 0.1371]])


### 1.3 - A partir de una secuencia

Para situaciones en las que necesites generar una secuencia de puntos de datos, como un rango de valores para probar las predicciones de un modelo, puedes crear un tensor directamente desde esa secuencia.

* `torch.arange()`: Crea un tensor 1D que contiene un rango de números desde el valor de inicio (start) especificado hasta uno menos que el valor final (stop) indicado, incrementando (si es positivo) o decrementando (si es negativo) según el valor de paso (step) especificado.

In [11]:
# Rango de números
range_tensor = torch.arange(0, 10, step=1)

print("ARANGE TENSOR:", range_tensor)

ARANGE TENSOR: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


## 2 - Cambio de Forma y Manipulación (Reshaping & Manipulating)

Una fuente muy común de errores en proyectos de PyTorch es la discrepancia entre la forma (shape) de tus datos de entrada y la forma que tu modelo espera. Por ejemplo, un modelo suele estar diseñado para procesar un lote (batch) de datos, por lo que incluso si quieres hacer una sola predicción, debes darle forma a tu tensor de entrada para que parezca un lote de uno. Dominar el "reshaping" de tensores es un paso clave para construir y depurar modelos de manera efectiva.

### 2.1 - Comprobación de las Dimensiones de un Tensor

El primer paso para solucionar una discrepancia de forma es entender las dimensiones actuales de tu tensor. Comprobar el shape es tu herramienta principal de depuración. Te indica cuántas muestras (samples) tienes y cuántas características (features) hay en cada muestra.

* `torch.Tensor.shape`: Un atributo que devuelve un objeto `torch.Size` detallando el tamaño del tensor a lo largo de cada dimensión.

In [12]:
# A 2D tensor
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

print("ORIGINAL TENSOR:\n\n", x)
print("\nTENSOR SHAPE:", x.shape)

ORIGINAL TENSOR:

 tensor([[1, 2, 3],
        [4, 5, 6]])

TENSOR SHAPE: torch.Size([2, 3])


### 2.2 - Cambio de las Dimensiones de un Tensor

Una vez que identificas una discrepancia de forma (shape mismatch), necesitas corregirla. Una tarea frecuente es añadir una dimensión a una sola muestra de datos para crear un lote de tamaño uno (batch of size one) para tu modelo, o eliminar una dimensión después de completar una operación por lotes.

* **Añadir Dimensión:** `torch.Tensor.unsqueeze()` inserta una nueva dimensión en el índice especificado.
    * *Nota cómo el shape cambiará de `[2, 3]` a `[1, 2, 3]` y el tensor queda envuelto en un par adicional de corchetes `[]`*.

In [14]:
print("ORIGINAL TENSOR:\n\n", x)
print("\nTENSOR SHAPE:", x.shape)
print("-"*45)

# Añadir dimensión
expanded = x.unsqueeze(0)  #  Añadir dimensión en el índice 0

print("\nTENSOR CON DIMENSIÓN AÑADIDA EN EL ÍNDICE 0:\n\n", expanded)
print("\nFORMA DEL TENSOR:", expanded.shape)

ORIGINAL TENSOR:

 tensor([[1, 2, 3],
        [4, 5, 6]])

TENSOR SHAPE: torch.Size([2, 3])
---------------------------------------------

TENSOR CON DIMENSIÓN AÑADIDA EN EL ÍNDICE 0:

 tensor([[[1, 2, 3],
         [4, 5, 6]]])

FORMA DEL TENSOR: torch.Size([1, 2, 3])


<br>

* **Eliminar Dimensión:** `torch.Tensor.squeeze()` elimina las dimensiones que tengan un tamaño de 1.
    * *Esto revierte la operación unsqueeze, eliminando el `1` del shape y quitando un par de corchetes exteriores*.

In [15]:
print("EXPANDED TENSOR:\n\n", expanded)
print("\nFORMA DEL TENSOR:", expanded.shape)
print("-"*45)

#  Eliminar dimensión 
squeezed = expanded.squeeze()
 
print("\nTENSOR CON DIMENSIÓN ELIMINADA:\n\n", squeezed)
print("\nFORMA DEL TENSOR:", squeezed.shape)

EXPANDED TENSOR:

 tensor([[[1, 2, 3],
         [4, 5, 6]]])

FORMA DEL TENSOR: torch.Size([1, 2, 3])
---------------------------------------------

TENSOR CON DIMENSIÓN ELIMINADA:

 tensor([[1, 2, 3],
        [4, 5, 6]])

FORMA DEL TENSOR: torch.Size([2, 3])


### 2.3 - Reestructuración (Restructuring)

Más allá de simplemente añadir o eliminar dimensiones, es posible que necesites cambiar completamente la estructura de un tensor para que coincida con los requisitos de una capa u operación específica dentro de tu red neuronal.

* **Cambio de forma (Reshaping):** `torch.Tensor.reshape()` cambia la forma de un tensor a las dimensiones especificadas.

In [16]:
print("ORIGINAL TENSOR:\n\n", x)
print("\nTENSOR SHAPE:", x.shape)
print("-"*45)

# Reshape
reshaped = x.reshape(3, 2)

print("\nAFTER PERFORMING reshape(3, 2):\n\n", reshaped)
print("\nTENSOR SHAPE:", reshaped.shape)

ORIGINAL TENSOR:

 tensor([[1, 2, 3],
        [4, 5, 6]])

TENSOR SHAPE: torch.Size([2, 3])
---------------------------------------------

AFTER PERFORMING reshape(3, 2):

 tensor([[1, 2],
        [3, 4],
        [5, 6]])

TENSOR SHAPE: torch.Size([3, 2])


* **Transposición (Transposing):** `torch.Tensor.transpose()` intercambia las dimensiones especificadas de un tensor.

In [17]:
print("ORIGINAL TENSOR:\n\n", x)
print("\nTENSOR SHAPE:", x.shape)
print("-"*45)

# Transpose
transposed = x.transpose(0, 1)

print("\nAFTER PERFORMING transpose(0, 1):\n\n", transposed)
print("\nTENSOR SHAPE:", transposed.shape)

ORIGINAL TENSOR:

 tensor([[1, 2, 3],
        [4, 5, 6]])

TENSOR SHAPE: torch.Size([2, 3])
---------------------------------------------

AFTER PERFORMING transpose(0, 1):

 tensor([[1, 4],
        [2, 5],
        [3, 6]])

TENSOR SHAPE: torch.Size([3, 2])


### 2.4 - Combinación de Tensores (Combining Tensors)

En la etapa de preparación de datos, es posible que necesites combinar datos de diferentes fuentes o fusionar lotes (batches) separados en un conjunto de datos más grande.

* `torch.cat()`: Une una secuencia de tensores a lo largo de una dimensión existente. Nota: Todos los tensores deben tener la misma forma (shape) en las dimensiones distintas a la que se está concatenando.

In [20]:
# Create two tensors to concatenate
tensor_a = torch.tensor([[1, 2],
                         [3, 4]])
tensor_b = torch.tensor([[5, 6],
                         [7, 8]])

# Concatenate along columns (dim=1)
concatenated_tensors = torch.cat((tensor_a, tensor_b), dim=1)


print("TENSOR A:\n\n", tensor_a)
print("\nTENSOR B:\n\n", tensor_b)
print("-"*45)
print("\nCONCATENATED TENSOR (dim=1):\n\n", concatenated_tensors)

TENSOR A:

 tensor([[1, 2],
        [3, 4]])

TENSOR B:

 tensor([[5, 6],
        [7, 8]])
---------------------------------------------

CONCATENATED TENSOR (dim=1):

 tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


## 3 - Indexación y Segmentación (Indexing & Slicing)

Una vez que tienes tus datos en un tensor, a menudo necesitarás acceder a partes específicas de ellos. Ya sea que estés tomando una única predicción para inspeccionar su valor, separando tus características de entrada (features) de tus etiquetas (labels), o seleccionando un subconjunto de datos para análisis, la indexación y la segmentación son las herramientas adecuadas para el trabajo.

### 3.1 - Acceso a los Elementos

Estas son las técnicas fundamentales para extraer datos de un tensor y funcionan de manera muy similar a cómo accederías a los elementos en una lista estándar de Python.

* **Indexación Estándar (Standard Indexing)**: Acceso a elementos individuales o filas completas utilizando índices enteros (por ejemplo, `x[0]`, `x[1, 2]`).

In [21]:
# Create a 3x4 tensor
x = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
print("ORIGINAL TENSOR:\n\n", x)
print("-" * 55)

# Get a single element at row 1, column 2
single_element_tensor = x[1, 2]

print("\nINDEXING SINGLE ELEMENT AT [1, 2]:", single_element_tensor)
print("-" * 55)

# Get the entire second row (index 1)
second_row = x[1]

print("\nINDEXING ENTIRE ROW [1]:", second_row)
print("-" * 55)

# Last row
last_row = x[-1]

print("\nINDEXING ENTIRE LAST ROW ([-1]):", last_row, "\n")

ORIGINAL TENSOR:

 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
-------------------------------------------------------

INDEXING SINGLE ELEMENT AT [1, 2]: tensor(7)
-------------------------------------------------------

INDEXING ENTIRE ROW [1]: tensor([5, 6, 7, 8])
-------------------------------------------------------

INDEXING ENTIRE LAST ROW ([-1]): tensor([ 9, 10, 11, 12]) 



<br>

* **Segmentación (Slicing)**: Extracción de sub-tensores utilizando la notación `[inicio:fin:paso]` (por ejemplo, `x[:2, ::2]`).
    * *Nota: El índice de fin (end) no se incluye en el resultado.*
* El slicing se puede utilizar para acceder a columnas completas.

In [22]:
print("ORIGINAL TENSOR:\n\n", x)
print("-" * 55)

# Get the first two rows
first_two_rows = x[0:2]

print("\nSLICING FIRST TWO ROWS ([0:2]):\n\n", first_two_rows)
print("-" * 55)

# Get the third column of all rows
third_column = x[:, 2]

print("\nSLICING THIRD COLUMN ([:, 2]]):", third_column)
print("-" * 55)

# Every other column
every_other_col = x[:, ::2]

print("\nEVERY OTHER COLUMN ([:, ::2]):\n\n", every_other_col)
print("-" * 55)

# Last column
last_col = x[:, -1]

print("\nLAST COLUMN ([:, -1]):", last_col, "\n")

ORIGINAL TENSOR:

 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
-------------------------------------------------------

SLICING FIRST TWO ROWS ([0:2]):

 tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
-------------------------------------------------------

SLICING THIRD COLUMN ([:, 2]]): tensor([ 3,  7, 11])
-------------------------------------------------------

EVERY OTHER COLUMN ([:, ::2]):

 tensor([[ 1,  3],
        [ 5,  7],
        [ 9, 11]])
-------------------------------------------------------

LAST COLUMN ([:, -1]): tensor([ 4,  8, 12]) 



* Combinación de Indexación y Segmentación

In [23]:
print("ORIGINAL TENSOR:\n\n", x)
print("-" * 55)

# Combining slicing and indexing (First two rows, last two columns)
combined = x[0:2, 2:]

print("\nFIRST TWO ROWS, LAST TWO COLS ([0:2, 2:]):\n\n", combined, "\n")

ORIGINAL TENSOR:

 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
-------------------------------------------------------

FIRST TWO ROWS, LAST TWO COLS ([0:2, 2:]):

 tensor([[3, 4],
        [7, 8]]) 



<br>

* **`.item()`**: Extrae el valor de un tensor de un solo elemento como un número estándar de Python.

In [24]:
print("SINGLE-ELEMENT TENSOR:", single_element_tensor)
print("-" * 45)

# Extract the value from a single-element tensor as a standard Python number
value = single_element_tensor.item()

print("\n.item() PYTHON NUMBER EXTRACTED:", value)
print("TYPE:", type(value))

SINGLE-ELEMENT TENSOR: tensor(7)
---------------------------------------------

.item() PYTHON NUMBER EXTRACTED: 7
TYPE: <class 'int'>


### 3.2 - Indexación Avanzada

Para una selección de datos más compleja, como filtrar tu conjunto de datos basándose en una o más condiciones, puedes utilizar técnicas de indexación avanzada.

* **Máscara Booleana (Boolean Masking)**: Uso de un tensor booleano para seleccionar elementos que cumplen una cierta condición (por ejemplo, `x[x > 5]`).

In [26]:
print("ORIGINAL TENSOR:\n\n", x)
print("-" * 55)

#  Indexación booleana usando comparaciones lógicas
mask = x > 6

print("MÁSCARA (VALORES > 6):\n\n", mask, "\n")

# Aplicando enmascaramiento booleano
mask_applied = x[mask]

print("VALORES DESPUÉS DE APLICAR LA MÁSCARA:", mask_applied, "\n")

ORIGINAL TENSOR:

 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
-------------------------------------------------------
MÁSCARA (VALORES > 6):

 tensor([[False, False, False, False],
        [False, False,  True,  True],
        [ True,  True,  True,  True]]) 

VALORES DESPUÉS DE APLICAR LA MÁSCARA: tensor([ 7,  8,  9, 10, 11, 12]) 



<br>

* **Indexación "Fancy" (Fancy Indexing)**: Uso de un tensor de índices para seleccionar elementos específicos de una manera no contigua.

In [ ]:
print("ORIGINAL TENSOR:\n\n", x)
print("-" * 55)

#  Indexación fancy

#  Obtener la primera y tercera filas
row_indices = torch.tensor([0, 2])

# Obtener la segunda y cuarta columnas
col_indices = torch.tensor([1, 3]) 

# Obtiene valores en (0,1), (0,3), (2,1), (2,3)
get_values = x[row_indices[:, None], col_indices]

print("\nELEMENTOS ESPECÍFICOS USANDO ÍNDICES:\n\n", get_values, "\n")

ORIGINAL TENSOR:

 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
-------------------------------------------------------

SPECIFIC ELEMENTS USING INDICES:

 tensor([[ 2,  4],
        [10, 12]]) 



## 4 - Operaciones Matemáticas y Lógicas (Mathematical & Logical Operations)

En su esencia, las redes neuronales realizan cálculos matemáticos. Un solo neurón, por ejemplo, calcula una suma ponderada de sus entradas y añade un sesgo (bias). PyTorch está optimizado para realizar estas operaciones de manera eficiente en tensores completos a la vez, lo que hace que el entrenamiento sea tan rápido.

### 4.1 - Aritmética

Estas operaciones son la base de cómo una red neuronal procesa los datos. Verás cómo PyTorch maneja cálculos elemento por elemento (element-wise) y utiliza una potente función llamada "broadcasting" para simplificar tu código.

* **Operaciones elemento por elemento (Element-wise Operations)**: Operadores matemáticos estándar (`+`, `*`) que se aplican a cada elemento de forma independiente.

In [30]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
print("TENSOR A:", a)
print("TENSOR B", b)
print("-" * 60)

# Element-wise addition
element_add = a + b

print("\nAFTER PERFORMING ELEMENT-WISE ADDITION:", element_add, "\n")

TENSOR A: tensor([1, 2, 3])
TENSOR B tensor([4, 5, 6])
------------------------------------------------------------

AFTER PERFORMING ELEMENT-WISE ADDITION: tensor([5, 7, 9]) 



In [31]:
print("TENSOR A:", a)
print("TENSOR B", b)
print("-" * 65)

# Element-wise multiplication
element_mul = a * b

print("\nAFTER PERFORMING ELEMENT-WISE MULTIPLICATION:", element_mul, "\n")

TENSOR A: tensor([1, 2, 3])
TENSOR B tensor([4, 5, 6])
-----------------------------------------------------------------

AFTER PERFORMING ELEMENT-WISE MULTIPLICATION: tensor([ 4, 10, 18]) 



<br>

* **Producto Punto (`torch.matmul()`)**: Calcula el producto punto (dot product) de dos vectores o matrices.

In [33]:
print("TENSOR A:", a)
print("TENSOR B:", b)
print("-" * 65)

# Dot product
dot_product = torch.matmul(a, b)

print("\nAFTER PERFORMING DOT PRODUCT:", dot_product, "\n")

TENSOR A: tensor([1, 2, 3])
TENSOR B: tensor([4, 5, 6])
-----------------------------------------------------------------

AFTER PERFORMING DOT PRODUCT: tensor(32) 



<br>

* **Broadcasting**: La expansión automática de tensores más pequeños para que coincidan con la forma (shape) de tensores más grandes durante las operaciones aritméticas.
    * El broadcasting permite realizar operaciones entre tensores con formas compatibles, incluso si no tienen exactamente las mismas dimensiones.

In [34]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([[1],
                 [2],
                 [3]])

print("TENSOR A:", a)
print("SHAPE:", a.shape)
print("\nTENSOR B\n\n", b)
print("\nSHAPE:", b.shape)
print("-" * 65)

# Apply broadcasting
c = a + b


print("\nTENSOR C:\n\n", c)
print("\nSHAPE:", c.shape, "\n")

TENSOR A: tensor([1, 2, 3])
SHAPE: torch.Size([3])

TENSOR B

 tensor([[1],
        [2],
        [3]])

SHAPE: torch.Size([3, 1])
-----------------------------------------------------------------

TENSOR C:

 tensor([[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]])

SHAPE: torch.Size([3, 3]) 



### 4.2 - Lógica y Comparaciones (Logic & Comparisons)

Las operaciones lógicas son herramientas potentes para la preparación y el análisis de datos. Te permiten crear máscaras booleanas para filtrar, seleccionar o modificar tus datos basándote en condiciones específicas que tú definas.

* **Operadores de Comparación**: Comparaciones elemento por elemento (element-wise) (`>`, `==`, `<`) que producen un tensor booleano.

In [35]:
temperatures = torch.tensor([20, 35, 19, 35, 42])
print("TEMPERATURES:", temperatures)
print("-" * 50)

### Comparison Operators (>, <, ==)

# Use '>' (greater than) to find temperatures above 30
is_hot = temperatures > 30

# Use '<=' (less than or equal to) to find temperatures 20 or below
is_cool = temperatures <= 20

# Use '==' (equal to) to find temperatures exactly equal to 35
is_35_degrees = temperatures == 35

print("\nHOT (> 30 DEGREES):", is_hot)
print("COOL (<= 20 DEGREES):", is_cool)
print("EXACTLY 35 DEGREES:", is_35_degrees, "\n")

TEMPERATURES: tensor([20, 35, 19, 35, 42])
--------------------------------------------------

HOT (> 30 DEGREES): tensor([False,  True, False,  True,  True])
COOL (<= 20 DEGREES): tensor([ True, False,  True, False, False])
EXACTLY 35 DEGREES: tensor([False,  True, False,  True, False]) 



<br>

* **Operadores Lógicos**: Operaciones lógicas elemento por elemento (`&` para **AND**, `|` para **OR**) en tensores booleanos.

In [36]:
is_morning = torch.tensor([True, False, False, True])
is_raining = torch.tensor([False, False, True, True])
print("IS MORNING:", is_morning)
print("IS RAINING:", is_raining)
print("-" * 50)

### Logical Operators (&, |)

# Use '&' (AND) to find when it's both morning and raining
morning_and_raining = (is_morning & is_raining)

# Use '|' (OR) to find when it's either morning or raining
morning_or_raining = is_morning | is_raining

print("\nMORNING & (AND) RAINING:", morning_and_raining)
print("MORNING | (OR) RAINING:", morning_or_raining)

IS MORNING: tensor([ True, False, False,  True])
IS RAINING: tensor([False, False,  True,  True])
--------------------------------------------------

MORNING & (AND) RAINING: tensor([False, False, False,  True])
MORNING | (OR) RAINING: tensor([ True, False,  True,  True])


### 4.3 - Estadísticas (Statistics)

Calcular estadísticas como la media o la desviación estándar puede ser útil para entender tu conjunto de datos o para implementar ciertos tipos de normalización durante la fase de preparación de datos.

* `torch.mean()`: Calcula la media de todos los elementos de un tensor.

In [37]:
data = torch.tensor([10.0, 20.0, 30.0, 40.0, 50.0])
print("DATA:", data)
print("-" * 45)

# Calculate the mean
data_mean = data.mean()

print("\nCALCULATED MEAN:", data_mean, "\n")

DATA: tensor([10., 20., 30., 40., 50.])
---------------------------------------------

CALCULATED MEAN: tensor(30.) 



<br>

* `torch.std()`: Calcula la desviación estándar de todos los elementos.

In [38]:
print("DATA:", data)
print("-" * 45)

# Calculate the standard deviation
data_std = data.std()

print("\nCALCULATED STD:", data_std, "\n")

DATA: tensor([10., 20., 30., 40., 50.])
---------------------------------------------

CALCULATED STD: tensor(15.8114) 



### 4.4 - Tipos de Datos (Data Types)

Tan importante como la forma (shape) de un tensor es su tipo de dato. Las redes neuronales suelen realizar sus cálculos utilizando números de punto flotante de 32 bits (float32). Proporcionar datos del tipo incorrecto, como un entero, puede provocar errores de ejecución o comportamientos inesperados durante el entrenamiento. Es una buena práctica asegurarse de que los tensores tengan el tipo de dato correcto para tu modelo.

* **Conversión de Tipo o Type Casting (`.int()`, etc.)**: Convierte un tensor de un tipo de dato a otro (por ejemplo, de float a integer).

In [39]:
print("DATA:", data)
print("DATA TYPE:", data.dtype)
print("-" * 45)

# Cast the tensor to a int type
int_tensor = data.int()

print("\nCASTED DATA:", int_tensor)
print("CASTED DATA TYPE", int_tensor.dtype)

DATA: tensor([10., 20., 30., 40., 50.])
DATA TYPE: torch.float32
---------------------------------------------

CASTED DATA: tensor([10, 20, 30, 40, 50], dtype=torch.int32)
CASTED DATA TYPE torch.int32


## 5 - Ejercicios Opcionales (Optional Exercises)

Ya has cubierto las herramientas esenciales para trabajar con tensores en PyTorch. La teoría proporciona el mapa, pero la práctica directa es lo que construye la verdadera confianza y habilidad. Los siguientes ejercicios opcionales son tu oportunidad para aplicar lo aprendido en escenarios prácticos, desde el análisis de datos de ventas hasta la ingeniería de nuevas características para un modelo de aprendizaje automático. Aquí es donde los conceptos realmente cobran vida, ¡así que sumérgete y pon a prueba tus nuevos conocimientos!

### Ejercicio 1: Análisis de Datos de Ventas Mensuales

Eres analista de datos en una empresa de comercio electrónico. Se te ha entregado un tensor que representa las ventas mensuales de tres productos diferentes durante un periodo de cuatro meses. Tu tarea es extraer información significativa de estos datos.

El tensor `sales_data` está estructurado de la siguiente manera:

* **Las filas** representan los **productos** (Producto A, Producto B, Producto C).
* **Las columnas** representan los **meses** (Ene, Feb, Mar, Abr).

**Tus objetivos son**:

1. Calcular las ventas totales del **Producto B** (la segunda fila).
2. Identificar qué meses tuvieron ventas **superiores a 130** para el **Producto C** (la tercera fila) utilizando una máscara booleana.
3. Extraer los datos de ventas de todos los productos para los meses de **Feb y Mar** (las dos columnas centrales).

<br>

<details>
<summary><span style="color:green;"><strong>Solución (Haz clic aquí para expandir)</strong></span></summary>

```python
### EMPIEZA EL CÓDIGO AQUÍ ###

# 1. Calcular las ventas totales para el Producto B.
total_sales_product_b = sales_data[1].sum()

# 2. Encontrar los meses donde las ventas del Producto C fueron > 130.
high_sales_mask_product_c = sales_data[2] > 130

# 3. Obtener las ventas de Feb y Mar para todos los productos.
sales_feb_mar = sales_data[:, 1:3]

### TERMINA EL CÓDIGO AQUÍ ###
```

In [40]:
# Datos de ventas de 3 productos durante 4 meses
sales_data = torch.tensor([[100, 120, 130, 110],   # Producto A
                           [ 90,  95, 105, 125],   # Producto B
                           [140, 115, 120, 150]    # Producto C
                          ], dtype=torch.float32)

print("DATOS DE VENTAS ORIGINALES:\n\n", sales_data)
print("-" * 45)

### EMPIEZA EL CÓDIGO AQUÍ ###

# 1. Calcular las ventas totales para el Producto B.
total_sales_product_b = sales_data[1].sum()

# 2. Encontrar los meses donde las ventas del Producto C fueron > 130.
high_sales_mask_product_c = sales_data[2] > 130

# 3. Obtener las ventas de Feb y Mar para todos los productos.
sales_feb_mar = sales_data[:, 1:3]

### TERMINA EL CÓDIGO AQUÍ ###

print("\nVentas Totales para el Producto B:               ", total_sales_product_b)
print("\nMeses con ventas >130 para el Producto C (Máscara): ", high_sales_mask_product_c)
print("\nVentas de Feb y Mar:\n\n", sales_feb_mar)

DATOS DE VENTAS ORIGINALES:

 tensor([[100., 120., 130., 110.],
        [ 90.,  95., 105., 125.],
        [140., 115., 120., 150.]])
---------------------------------------------

Ventas Totales para el Producto B:                tensor(415.)

Meses con ventas >130 para el Producto C (Máscara):  tensor([ True, False, False,  True])

Ventas de Feb y Mar:

 tensor([[120., 130.],
        [ 95., 105.],
        [115., 120.]])


#### Expected Output:

```
Ventas Totales para el Producto B:                       tensor(415.)

Meses con ventas >130 para el Producto C (Máscara):      tensor([ True, False, False,  True])

Ventas de Feb y Mar:

 tensor([[120., 130.],
        [ 95., 105.],
        [115., 120.]])
```

### Ejercicio 2: Transformación de Lotes de Imágenes (Image Batch Transformation)

Estás trabajando en un modelo de visión artificial y tienes un lote de 4 imágenes en escala de grises, cada una de un tamaño de 3x3 píxeles. Los datos están actualmente en un tensor con la forma `[4, 3, 3]`, que representa `[batch_size, height, width]`.

Para el procesamiento con ciertos frameworks de deep learning, necesitas transformar estos datos al formato `[batch_size, channels, height, width]`. Dado que las imágenes son en escala de grises, **tendrás que**:

1. Añadir una nueva dimensión de tamaño 1 en el índice 1 para representar el canal de color (channel).
2. Después de añadir el canal, te das cuenta de que el modelo espera la forma `[batch_size, height, width, channels]`. Transpón el tensor para intercambiar la dimensión del canal con la última dimensión.

<br>

<details>
<summary><span style="color:green;"><strong>Solución (Haz clic aquí para expandir)</strong></span></summary>

```python
### EMPIEZA EL CÓDIGO AQUÍ ###

# 1. Añadir una dimensión de canal en el índice 1.
image_batch_with_channel = image_batch.unsqueeze(1)

# 2. Trasponer el tensor para mover la dimensión del canal al final.
# Intercambiar la dimensión 1 (channels) con la dimensión 3 (la última).
image_batch_transposed = image_batch_with_channel.transpose(1, 3)

### TERMINA EL CÓDIGO AQUÍ ###
```

In [57]:
# Un lote de 4 imágenes en escala de grises, cada una de 3x3
image_batch = torch.rand(4, 3, 3)

print("\nLOTE DE IMÁGENES EN ESCALA DE GRISES:\n\n", image_batch)

print("FORMA DEL LOTE ORIGINAL:", image_batch.shape)
print("-" * 45)

### EMPIEZA EL CÓDIGO AQUÍ ###

# 1. Añadir una dimensión de canal en el índice 1.
image_batch_with_channel = image_batch.unsqueeze(1)

# 2. Trasponer el tensor para mover la dimensión del canal al final.
# Intercambiar la dimensión 1 (channels) con la dimensión 3 (la última).
image_batch_transposed = image_batch_with_channel.transpose(1, 3)

### TERMINA EL CÓDIGO AQUÍ ###


print("\nFORMA DESPUÉS DE UNSQUEEZE:", image_batch_with_channel.shape)
print("FORMA DESPUÉS DE TRANSPOSE:", image_batch_transposed.shape)


LOTE DE IMÁGENES EN ESCALA DE GRISES:

 tensor([[[0.6649, 0.4313, 0.2238],
         [0.4656, 0.2469, 0.3819],
         [0.9608, 0.7149, 0.2105]],

        [[0.1026, 0.2332, 0.3063],
         [0.6521, 0.2463, 0.2972],
         [0.1306, 0.4289, 0.1610]],

        [[0.5198, 0.9949, 0.8336],
         [0.8663, 0.3064, 0.2282],
         [0.5162, 0.4791, 0.1601]],

        [[0.1155, 0.5101, 0.8326],
         [0.8483, 0.7045, 0.8764],
         [0.3790, 0.6014, 0.8257]]])
FORMA DEL LOTE ORIGINAL: torch.Size([4, 3, 3])
---------------------------------------------

FORMA DESPUÉS DE UNSQUEEZE: torch.Size([4, 1, 3, 3])
FORMA DESPUÉS DE TRANSPOSE: torch.Size([4, 3, 3, 1])


#### Expected Output:

```
SHAPE AFTER UNSQUEEZE: torch.Size([4, 1, 3, 3])
SHAPE AFTER TRANSPOSE: torch.Size([4, 3, 3, 1])
```

### Ejercicio 3: Combinación y Ponderación de Datos de Sensores (Combining and Weighting Sensor Data)

Estás construyendo un sistema de monitoreo ambiental que utiliza dos sensores: uno para la temperatura y otro para la humedad. Recibes los datos de estos sensores como dos tensores 1D separados.

**Tu tarea es**:

1. **Concatenar** los dos tensores en un único tensor de `2x5`, donde la primera fila sean los datos de temperatura y la segunda los de humedad.
2. Crear un tensor de pesos (`weights`) `torch.tensor([0.6, 0.4])`.
3. Utilizar **broadcasting y multiplicación elemento por elemento** para aplicar estos pesos a los datos combinados de los sensores. Los datos de temperatura deben multiplicarse por 0.6 y los de humedad por 0.4.
4. Finalmente, calcular el **promedio ponderado** para cada paso de tiempo **sumando** los valores ponderados a lo largo de `dim=0` y **dividiendo** por la suma de los pesos.

<br>

<details>
<summary><span style="color:green;"><strong>Solución (Haz clic aquí para expandir)</strong></span></summary>

```python
### EMPIEZA EL CÓDIGO AQUÍ ###

# 1. Concatenar los dos tensores.
# Nota: Primero necesitas usar unsqueeze para apilarlos verticalmente.
combined_data = torch.cat((temperature.unsqueeze(0), humidity.unsqueeze(0)), dim=0)

# 2. Crear el tensor de pesos.
weights = torch.tensor([0.6, 0.4])

# 3. Aplicar los pesos usando broadcasting.
# Necesitas cambiar la forma (reshape) de los pesos a [2, 1] para hacer el broadcast a través de las columnas.
weighted_data = combined_data * weights.unsqueeze(1)

# 4. Calcular el promedio ponderado para cada paso de tiempo.
#    (Un promedio real = suma ponderada / suma de los pesos)
weighted_sum = torch.sum(weighted_data, dim=0)
weighted_average = weighted_sum / torch.sum(weights)

### TERMINA EL CÓDIGO AQUÍ ###
```

In [66]:
# Lecturas de sensores (5 pasos de tiempo)
temperature = torch.tensor([22.5, 23.1, 21.9, 22.8, 23.5])
humidity = torch.tensor([55.2, 56.4, 54.8, 57.1, 56.8])

print("DATOS DE TEMPERATURA: ", temperature)
print("DATOS DE HUMEDAD:     ", humidity)
print("-" * 45)

### EMPIEZA EL CÓDIGO AQUÍ ###

# 1. Concatenar los dos tensores.
# Nota: Necesitas usar unsqueeze primero para apilarlos verticalmente.
combined_data = torch.cat([temperature.unsqueeze(0), humidity.unsqueeze(0)], dim=0)

# 2. Crear el tensor de pesos (weights).
weights = torch.tensor([0.6, 0.4])

# 3. Aplicar los pesos usando broadcasting.
# Necesitas cambiar la forma de los pesos a [2, 1] para hacer el broadcast por columnas.
weighted_data = combined_data * weights.unsqueeze(1)

# 4. Calcular el promedio ponderado para cada paso de tiempo.
#    (Un promedio real = suma ponderada / suma de los pesos)
weighted_sum = weighted_data.sum(dim=0)
weighted_average = weighted_sum / weights.sum()

### TERMINA EL CÓDIGO AQUÍ ###

print("\nDATOS COMBINADOS (2x5):\n\n", combined_data)
print("\nDATOS PONDERADOS:\n\n", weighted_data)
print("\nPROMEDIO PONDERADO:", weighted_average)

DATOS DE TEMPERATURA:  tensor([22.5000, 23.1000, 21.9000, 22.8000, 23.5000])
DATOS DE HUMEDAD:      tensor([55.2000, 56.4000, 54.8000, 57.1000, 56.8000])
---------------------------------------------

DATOS COMBINADOS (2x5):

 tensor([[22.5000, 23.1000, 21.9000, 22.8000, 23.5000],
        [55.2000, 56.4000, 54.8000, 57.1000, 56.8000]])

DATOS PONDERADOS:

 tensor([[13.5000, 13.8600, 13.1400, 13.6800, 14.1000],
        [22.0800, 22.5600, 21.9200, 22.8400, 22.7200]])

PROMEDIO PONDERADO: tensor([35.5800, 36.4200, 35.0600, 36.5200, 36.8200])


#### Expected Output:

```
COMBINED DATA (2x5):

 tensor([[22.5000, 23.1000, 21.9000, 22.8000, 23.5000],
        [55.2000, 56.4000, 54.8000, 57.1000, 56.8000]])

WEIGHTED DATA:

 tensor([[13.5000, 13.8600, 13.1400, 13.6800, 14.1000],
        [22.0800, 22.5600, 21.9200, 22.8400, 22.7200]])

WEIGHTED AVERAGE: tensor([35.5800, 36.4200, 35.0600, 36.5200, 36.8200])
```

### Ejercicio 4: Ingeniería de Características para Tarifas de Taxi (Feature Engineering for Taxi Fares)

Estás trabajando con un conjunto de datos de viajes en taxi. Tienes un tensor, `trip_data`, donde cada fila es un viaje y las columnas representan **[distancia (km), hora_del_día (24h)]**.

**Tu objetivo** es crear una nueva característica binaria llamada `is_rush_hour_long_trip`. Esta característica debe ser `True` (o `1`) solo si un viaje cumple con **ambos** de los siguientes criterios:

* Es un **viaje largo** (distancia > 10 km).
* Ocurre durante una **hora punta** (8-10 AM o 5-7 PM, es decir, `[8, 10)` o `[17, 19)`).

Para lograr esto, necesitarás:

1. **Segmentar (Slice)** el tensor `trip_data` para aislar las columnas de `distance` y `hour`.
2. Usar **operadores lógicos y de comparación** para crear máscaras booleanas para cada condición (viaje largo, hora punta matutina, hora punta vespertina).
3. Combinar estas máscaras para crear la característica final `is_rush_hour_long_trip`.
4. **Cambiar la forma (Reshape)** de este nuevo tensor de característica 1D a un vector de columna 2D y convertir su tipo de dato a float para que pueda combinarse con los datos originales.

<br>

<details>
<summary><span style="color:green;"><strong>Solución (Haz clic aquí para expandir)</strong></span></summary>

```python
### EMPIEZA EL CÓDIGO AQUÍ ###

# 1. Segmentar el tensor principal para obtener tensores 1D para cada característica.
distances = trip_data[:, 0]
hours = trip_data[:, 1]

# 2. Crear máscaras booleanas para cada condición.
is_long_trip = distances > 10.0
is_morning_rush = (hours >= 8.0) & (hours < 10.0)
is_evening_rush = (hours >= 17.0) & (hours < 19.0)

# 3. Combinar máscaras para identificar viajes largos en hora punta.
# Un viaje es un "rush hour long trip" si es (hora punta matutina O vespertina) Y un viaje largo.
is_rush_hour_long_trip_mask = (is_morning_rush | is_evening_rush) & is_long_trip

# 4. Cambiar la forma de la nueva característica a un vector de columna y convertir a float.
new_feature_col = is_rush_hour_long_trip_mask.float().unsqueeze(1)

### TERMINA EL CÓDIGO AQUÍ ###
```

In [74]:
# Datos de 8 viajes en taxi: [distancia, hora_del_día]
trip_data = torch.tensor([
    [5.3, 7],   # Ni hora punta, ni largo
    [12.1, 9],  # Hora punta mañana, viaje largo -> RUSH HOUR LONG
    [15.5, 13], # Ni hora punta, viaje largo
    [6.7, 18],  # Hora punta tarde, no largo
    [2.4, 20],  # Ni hora punta, ni largo
    [11.8, 17], # Hora punta tarde, viaje largo -> RUSH HOUR LONG
    [9.0, 9],   # Hora punta mañana, no largo
    [14.2, 8]   # Hora punta mañana, viaje largo -> RUSH HOUR LONG
], dtype=torch.float32)


print("DATOS DE VIAJES ORIGINALES (Distancia, Hora):\n\n", trip_data)
print("-" * 55)


### EMPIEZA EL CÓDIGO AQUÍ ###

# 1. Segmentar el tensor principal para obtener tensores 1D para cada característica.
distances = trip_data[:, 0]
hours = trip_data[:, 1]

# 2. Crear máscaras booleanas para cada condición.
is_long_trip = hours > 10
is_morning_rush = ((hours >= 7) & (hours <= 9))
is_evening_rush = ((hours >= 16) & (hours <= 19))

# 3. Combinar máscaras para identificar viajes largos en hora punta.
# Un viaje es largo en hora punta si es (punta mañana O punta tarde) Y un viaje largo.
is_rush_hour_long_trip_mask = is_long_trip & (is_morning_rush | is_evening_rush)

# 4. Cambiar la forma de la nueva característica a un vector de columna y convertir a float.
new_feature_col = is_rush_hour_long_trip_mask.unsqueeze(1).float()

### TERMINA EL CÓDIGO AQUÍ ###

print("\nMÁSCARA 'IS RUSH HOUR LONG TRIP': ", is_rush_hour_long_trip_mask)
print("\nCOLUMNA DE NUEVA CARACTERÍSTICA (Redimensionada):\n\n", new_feature_col)

# Ahora puedes concatenar esta nueva característica a los datos originales
enhanced_trip_data = torch.cat((trip_data, new_feature_col), dim=1)
print("\nDATOS MEJORADOS (con la nueva característica al final):\n\n", enhanced_trip_data)

DATOS DE VIAJES ORIGINALES (Distancia, Hora):

 tensor([[ 5.3000,  7.0000],
        [12.1000,  9.0000],
        [15.5000, 13.0000],
        [ 6.7000, 18.0000],
        [ 2.4000, 20.0000],
        [11.8000, 17.0000],
        [ 9.0000,  9.0000],
        [14.2000,  8.0000]])
-------------------------------------------------------

MÁSCARA 'IS RUSH HOUR LONG TRIP':  tensor([False, False, False,  True, False,  True, False, False])

COLUMNA DE NUEVA CARACTERÍSTICA (Redimensionada):

 tensor([[0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.]])

DATOS MEJORADOS (con la nueva característica al final):

 tensor([[ 5.3000,  7.0000,  0.0000],
        [12.1000,  9.0000,  0.0000],
        [15.5000, 13.0000,  0.0000],
        [ 6.7000, 18.0000,  1.0000],
        [ 2.4000, 20.0000,  0.0000],
        [11.8000, 17.0000,  1.0000],
        [ 9.0000,  9.0000,  0.0000],
        [14.2000,  8.0000,  0.0000]])


#### Expected Output:

```
'IS RUSH HOUR LONG TRIP' MASK:  tensor([False,  True, False, False, False,  True, False,  True])

NEW FEATURE COLUMN (Reshaped):

 tensor([[0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.]])

ENHANCED DATA (with new feature at the end):

 tensor([[ 5.3000,  7.0000,  0.0000],
        [12.1000,  9.0000,  1.0000],
        [15.5000, 13.0000,  0.0000],
        [ 6.7000, 18.0000,  0.0000],
        [ 2.4000, 20.0000,  0.0000],
        [11.8000, 17.0000,  1.0000],
        [ 9.0000,  9.0000,  0.0000],
        [14.2000,  8.0000,  1.0000]])
```        

## Conclusión (Conclusion)

¡Felicitaciones por completar este laboratorio! Ahora has trabajado con los bloques de construcción fundamentales de PyTorch. Comenzaste desde cero y aprendiste a crear, redimensionar, combinar y consultar tensores de diversas maneras.

Las habilidades que has desarrollado aquí son esenciales para todo practicante de machine learning. La aritmética elemento por elemento (element-wise) y el broadcasting que practicaste son precisamente la forma en que una red neuronal aplica eficientemente pesos (weights) y sesgos (biases) a lotes enteros de datos a la vez. Las técnicas de redimensionamiento como `unsqueeze` y `squeeze` son las que te permiten preparar un solo punto de datos para un modelo que espera un lote (batch), y luego limpiar la salida después. Estos no son solo ejercicios abstractos; son las operaciones diarias necesarias para construir y depurar modelos de deep learning efectivos.

Con este sólido conocimiento de los tensores, estás plenamente preparado para pasar a la siguiente etapa: construir y entrenar redes neuronales para resolver problemas aún más complejos. Cada modelo que construyas de ahora en adelante se apoyará sobre esta base.